import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube,} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Farnaz Fawad Hasan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10">
        <section className= "min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-burtons'>develpoedbyfarnaz</h1>
            <ul className="flex items-center">
              <li>
                 <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                 <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2
                 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>

          </nav>
          <div className="text-center p-10 ">
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Farnaz Fawad Hasan</h2>
            <h3 className='text-2xl py-2 '>Developer and Designer.</h3>
            <p className='text-md py-5 leading-8  text-gray-800'>Meet Farnaz, a passionate advocate for community engagement and sustainable development. With a background in environmental science and project management, she's driven to create positive change through collaborative initiatives. From clean-up campaigns to education programs, Farnaz is dedicated to fostering unity and empowerment. Join her on a journey of impactful transformation.</p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin />
            <AiFillYoutube />

          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout = "fill" objectFit="cover" />


          </div>

        </section>

{/* Start of Section 2 */}

        <section>
          <div>
          <h3 className="text-3xl py-1">Services I offer</h3>
          <p className='text-md py-5 leading-8  text-gray-800'>
          Farnaz offers a range of dynamic services that reflect her expertise and passions. 
          From <span className='text-teal-500'>crafting</span> captivating websites and user-friendly mobile applications to offering insightful tech consultations, she's your go-to resource for all things tech. With a knack for simplifying the complex, Farnaz also conducts interactive coding workshops and provides comprehensive project management to ensure seamless execution. Beyond the tech realm, her commitment extends to environmental consulting, where she shares sustainable practices and empowers positive change. Whether you're seeking innovative digital solutions or aiming to foster community engagement, Farnaz is here to guide you on a journey of growth and transformation.

          </p>

          </div>

          <div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>

            </div>

          </div>
        </section>

      </main>
         
    </div>
      
    
  );
}



